Update language-data from upstream
wikimedia/jquery.uls pull request #493
Opened 2024-10-17 21:07 UTC by nemoralis

* Update Central Dusun autonym

https://phabricator.wikimedia.org/T375891

2024-10-17 21:27 UTC, amire80 commented
Did you do it by manually editing the file or by running the fetch-language-data.sh script?

2024-10-18 08:27 UTC, nemoralis commented
Manual, I didn't know there was a script for this until you mentioned it. I ran the script but nothing changed. It seems I did it correct manually.

2024-10-18 16:28 UTC, srish requested changes
@nemoralis Usually, we update language data from upstream using `./scripts/fetch-language-data.sh` to pull in any recent changes. If you perform a git pull in the repo and then run the script, you'll notice several other updates as well.

2024-10-19 16:45 UTC, amire80 approved these changes

2024-10-19 16:46 UTC, amire80 approved these changes

2024-10-19 16:47 UTC, merged